-- Inference pipeline tables and views
-- These objects support the workshop inference workflow
-- Template variables: {database}, {schema}

-- PREDICTIONS table: Stores model predictions with actual outcomes for evaluation
CREATE TABLE IF NOT EXISTS {database}.{schema}.PREDICTIONS (
    PREDICTION_ID INTEGER AUTOINCREMENT PRIMARY KEY,
    PUDO_ID INTEGER NOT NULL,
    PREDICTION_DATE DATE NOT NULL,
    PREDICTED_FILL_RATE FLOAT NOT NULL,
    MODEL_VERSION VARCHAR(100) NOT NULL,
    PREDICTION_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    ACTUAL_FILL_RATE FLOAT,
    PREDICTION_ERROR FLOAT,
    FOREIGN KEY (PUDO_ID) REFERENCES {database}.SHARED_DATA.PUDO_REFERENCE(PUDO_ID),
    UNIQUE (PUDO_ID, PREDICTION_DATE, MODEL_VERSION)
);

-- Note: DATA_GENERATION_LOG is in SHARED_DATA schema since it tracks
-- simulation state that should be shared across all environments

-- PUDO_ALERTS view: High-risk PUDOs requiring attention (predicted fill > 85%)
CREATE OR REPLACE VIEW {database}.{schema}.PUDO_ALERTS AS
SELECT
    p.PREDICTION_ID,
    p.PUDO_ID,
    pr.PUDO_NAME,
    pr.PUDO_TYPE,
    p.PREDICTION_DATE,
    p.PREDICTED_FILL_RATE,
    pr.CAPACITY,
    ROUND(p.PREDICTED_FILL_RATE * pr.CAPACITY) AS PREDICTED_OCCUPANCY,
    p.MODEL_VERSION,
    p.PREDICTION_TIMESTAMP
FROM {database}.{schema}.PREDICTIONS p
JOIN {database}.SHARED_DATA.PUDO_REFERENCE pr ON p.PUDO_ID = pr.PUDO_ID
WHERE p.PREDICTED_FILL_RATE > 0.85
  AND p.ACTUAL_FILL_RATE IS NULL
ORDER BY p.PREDICTED_FILL_RATE DESC;

-- INFERENCE_METRICS view: Prediction accuracy metrics for monitoring
CREATE OR REPLACE VIEW {database}.{schema}.INFERENCE_METRICS AS
SELECT
    p.PREDICTION_DATE,
    p.MODEL_VERSION,
    COUNT(*) AS TOTAL_PREDICTIONS,
    COUNT(p.ACTUAL_FILL_RATE) AS PREDICTIONS_WITH_ACTUALS,
    AVG(p.PREDICTION_ERROR) AS MEAN_ERROR,
    AVG(ABS(p.PREDICTION_ERROR)) AS MEAN_ABSOLUTE_ERROR,
    SQRT(AVG(POWER(p.PREDICTION_ERROR, 2))) AS RMSE,
    MIN(p.PREDICTION_ERROR) AS MIN_ERROR,
    MAX(p.PREDICTION_ERROR) AS MAX_ERROR,
    SUM(CASE WHEN p.PREDICTION_ERROR > 0 THEN 1 ELSE 0 END) AS OVER_PREDICTIONS,
    SUM(CASE WHEN p.PREDICTION_ERROR < 0 THEN 1 ELSE 0 END) AS UNDER_PREDICTIONS
FROM {database}.{schema}.PREDICTIONS p
WHERE p.ACTUAL_FILL_RATE IS NOT NULL
GROUP BY p.PREDICTION_DATE, p.MODEL_VERSION
ORDER BY p.PREDICTION_DATE DESC;
