-- Grant object creation privileges on all schemas
GRANT CREATE TABLE ON ALL SCHEMAS IN DATABASE {database_name} TO ROLE {role_name};
GRANT CREATE VIEW ON ALL SCHEMAS IN DATABASE {database_name} TO ROLE {role_name};
GRANT CREATE STAGE ON ALL SCHEMAS IN DATABASE {database_name} TO ROLE {role_name};
GRANT CREATE FILE FORMAT ON ALL SCHEMAS IN DATABASE {database_name} TO ROLE {role_name};
GRANT CREATE FUNCTION ON ALL SCHEMAS IN DATABASE {database_name} TO ROLE {role_name};
GRANT CREATE PROCEDURE ON ALL SCHEMAS IN DATABASE {database_name} TO ROLE {role_name};
GRANT CREATE SEQUENCE ON ALL SCHEMAS IN DATABASE {database_name} TO ROLE {role_name};
GRANT CREATE PIPE ON ALL SCHEMAS IN DATABASE {database_name} TO ROLE {role_name};
GRANT CREATE STREAM ON ALL SCHEMAS IN DATABASE {database_name} TO ROLE {role_name};
GRANT CREATE TASK ON ALL SCHEMAS IN DATABASE {database_name} TO ROLE {role_name};
GRANT CREATE MODEL ON ALL SCHEMAS IN DATABASE {database_name} TO ROLE {role_name};
GRANT CREATE DATASET ON ALL SCHEMAS IN DATABASE {database_name} TO ROLE {role_name};

-- Grant on future schemas
GRANT CREATE TABLE ON FUTURE SCHEMAS IN DATABASE {database_name} TO ROLE {role_name};
GRANT CREATE VIEW ON FUTURE SCHEMAS IN DATABASE {database_name} TO ROLE {role_name};
GRANT CREATE STAGE ON FUTURE SCHEMAS IN DATABASE {database_name} TO ROLE {role_name};
GRANT CREATE FILE FORMAT ON FUTURE SCHEMAS IN DATABASE {database_name} TO ROLE {role_name};
GRANT CREATE FUNCTION ON FUTURE SCHEMAS IN DATABASE {database_name} TO ROLE {role_name};
GRANT CREATE PROCEDURE ON FUTURE SCHEMAS IN DATABASE {database_name} TO ROLE {role_name};
GRANT CREATE SEQUENCE ON FUTURE SCHEMAS IN DATABASE {database_name} TO ROLE {role_name};
GRANT CREATE PIPE ON FUTURE SCHEMAS IN DATABASE {database_name} TO ROLE {role_name};
GRANT CREATE STREAM ON FUTURE SCHEMAS IN DATABASE {database_name} TO ROLE {role_name};
GRANT CREATE TASK ON FUTURE SCHEMAS IN DATABASE {database_name} TO ROLE {role_name};
GRANT CREATE MODEL ON FUTURE SCHEMAS IN DATABASE {database_name} TO ROLE {role_name};
GRANT CREATE DATASET ON FUTURE SCHEMAS IN DATABASE {database_name} TO ROLE {role_name};
