-- Grant privileges on all existing and future objects
GRANT ALL PRIVILEGES ON ALL TABLES IN DATABASE {database_name} TO ROLE {role_name};
GRANT ALL PRIVILEGES ON ALL VIEWS IN DATABASE {database_name} TO ROLE {role_name};
GRANT ALL PRIVILEGES ON ALL STAGES IN DATABASE {database_name} TO ROLE {role_name};
GRANT ALL PRIVILEGES ON ALL FILE FORMATS IN DATABASE {database_name} TO ROLE {role_name};
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN DATABASE {database_name} TO ROLE {role_name};
GRANT ALL PRIVILEGES ON ALL PROCEDURES IN DATABASE {database_name} TO ROLE {role_name};
GRANT ALL PRIVILEGES ON ALL STREAMS IN DATABASE {database_name} TO ROLE {role_name};
GRANT ALL PRIVILEGES ON ALL TASKS IN DATABASE {database_name} TO ROLE {role_name};

-- Grant on future objects
GRANT ALL PRIVILEGES ON FUTURE TABLES IN DATABASE {database_name} TO ROLE {role_name};
GRANT ALL PRIVILEGES ON FUTURE VIEWS IN DATABASE {database_name} TO ROLE {role_name};
GRANT ALL PRIVILEGES ON FUTURE STAGES IN DATABASE {database_name} TO ROLE {role_name};
GRANT ALL PRIVILEGES ON FUTURE FILE FORMATS IN DATABASE {database_name} TO ROLE {role_name};
GRANT ALL PRIVILEGES ON FUTURE FUNCTIONS IN DATABASE {database_name} TO ROLE {role_name};
GRANT ALL PRIVILEGES ON FUTURE PROCEDURES IN DATABASE {database_name} TO ROLE {role_name};
GRANT ALL PRIVILEGES ON FUTURE STREAMS IN DATABASE {database_name} TO ROLE {role_name};
GRANT ALL PRIVILEGES ON FUTURE TASKS IN DATABASE {database_name} TO ROLE {role_name};
