-- Core PUDO data tables
-- These tables store the primary workshop data for logistics simulation
-- Template variables: {database}, {schema}

-- PUDO Reference table: Physical pickup/dropoff locations
CREATE TABLE IF NOT EXISTS {database}.{schema}.PUDO_REFERENCE (
    PUDO_ID INTEGER PRIMARY KEY,
    PUDO_NAME VARCHAR(50) NOT NULL,
    PUDO_TYPE VARCHAR(20) NOT NULL,
    LATITUDE FLOAT NOT NULL,
    LONGITUDE FLOAT NOT NULL,
    ADDRESS VARCHAR(500),
    CAPACITY INTEGER NOT NULL,
    OPENING_HOURS VARCHAR(50),
    IS_ACTIVE BOOLEAN NOT NULL,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Parcels table: Customer packages
CREATE TABLE IF NOT EXISTS {database}.{schema}.PARCELS (
    TRACKING_NUMBER VARCHAR(50) PRIMARY KEY,
    DESTINATION_LAT FLOAT NOT NULL,
    DESTINATION_LON FLOAT NOT NULL,
    DESTINATION_ADDRESS VARCHAR(500),
    PARCEL_SIZE VARCHAR(10) NOT NULL,
    WEIGHT_KG FLOAT NOT NULL,
    CREATED_DATE DATE NOT NULL,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Delivery Attempts table: Multi-attempt delivery lifecycle
CREATE TABLE IF NOT EXISTS {database}.{schema}.DELIVERY_ATTEMPTS (
    ATTEMPT_ID VARCHAR(50) PRIMARY KEY,
    TRACKING_NUMBER VARCHAR(50) NOT NULL,
    ATTEMPT_DATE DATE NOT NULL,
    ATTEMPT_NUMBER INTEGER NOT NULL,
    DELIVERY_STATUS VARCHAR(50) NOT NULL,
    PUDO_ID INTEGER,
    DRIVER_ID INTEGER NOT NULL,
    ATTEMPT_TIME TIME NOT NULL,
    FAILURE_REASON VARCHAR(100),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    FOREIGN KEY (TRACKING_NUMBER)
        REFERENCES {database}.{schema}.PARCELS(TRACKING_NUMBER),
    FOREIGN KEY (PUDO_ID) REFERENCES {database}.{schema}.PUDO_REFERENCE(PUDO_ID)
);

-- PUDO Occupancy table: Daily capacity utilization
CREATE TABLE IF NOT EXISTS {database}.{schema}.PUDO_OCCUPANCY (
    PUDO_ID INTEGER NOT NULL,
    DATE DATE NOT NULL,
    DAILY_DELIVERIES INTEGER NOT NULL,
    FILL_RATE FLOAT NOT NULL,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    FOREIGN KEY (PUDO_ID) REFERENCES {database}.{schema}.PUDO_REFERENCE(PUDO_ID),
    UNIQUE (PUDO_ID, DATE)
);

-- DATA_GENERATION_LOG table: Tracks incremental data generation runs
-- This is shared across all environments to maintain simulation state
CREATE TABLE IF NOT EXISTS {database}.{schema}.DATA_GENERATION_LOG (
    LOG_ID INTEGER AUTOINCREMENT PRIMARY KEY,
    SIMULATION_DATE DATE NOT NULL,
    REAL_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PHASE VARCHAR(20) NOT NULL,
    RECORDS_ADDED INTEGER NOT NULL,
    STATUS VARCHAR(20) NOT NULL,
    NOTES VARCHAR(500),
    UNIQUE (SIMULATION_DATE, PHASE)
);
